# Site Settings
title: Neonime
email: taniarascia@gmail.com
description: longentod
#description: >
#A guide to getting started with Jekyll.
#baseurl: "/startjekyll"
#url: https://neonime.github.io
notelp: 085726074357
favicon_url: 
twitter_username: itclax
github_username:  neonime

#featured
year: 
 - 2010
 - 2011
 - 2012
 - 2013
 - 2014
 - 2015
 - 2016
 - 2017
 - 2018
 - 2019

genre: 
 - Romance
 - Adventure
 - Fantasy
 - Other

#socialmedia
url_facebookmu: https://fb.com/itclax
nama_facebookmu: itclax
nama_twittermu: itclax
url_twittermu: https://twitter.com/itclax
url_googlemu: https://google.com
nama_googlemu: yuyun_ryuuzaki
url_dribbble: https://gaada
nama_dribbble: gaada
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
plugins:
 - jekyll-admin
 - jekyll-paginate-v2

kramdown:
  input: GFM
  
# Pagination Settings
pagination:
  enabled: true

#paginate: 2
#paginate_path: /blog/page/:num
permalink: /:title.html
